Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Layout/TrailingBlankLines:
  EnforcedStyle: final_blank_line

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/SpaceAroundOperators:
  AllowForAlignment: false

Style/ConditionalAssignment:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
AllCops:
  Exclude:
    - 'db/schema.rb'

